Add Ruby 3.1, 3.2, 3.3 to CI
 - Bump Rake dev dependency due to "rake aborted!
NoMethodError: undefined method `=~' for an instance of Proc
/Users/....../3.3.0/bin/bundle:25:in `load'"